name: Build Docker image

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres: [9, 10, 11, 12]
    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image
        uses: actions/docker/cli@master
        with:
          args: build --file Dockerfile --tag ${DOCKER_IMAGE_NAME}:${{ matrix.postgres }} ${{ matrix.postgres }}/.
        env:
          DOCKER_IMAGE_NAME: postgres
